import {
  UserOutlined,
  ShopOutlined,
  PartitionOutlined,
  ProductOutlined,
  SettingOutlined,
  ShoppingCartOutlined,
  ProfileOutlined,
  AlertOutlined,
  TagOutlined,
  ProjectOutlined,
  TagsOutlined,
  PullRequestOutlined
} from "@ant-design/icons";
const APP_PREFIX_PATH = "/admin";

const adminNav = [
  {
    key: "admin",
    title: "sidenav.admin",
    breadcrumb: false,
    isGroupTitle: true,
    submenu: [
      {
        key: "customer",
        path: `${APP_PREFIX_PATH}/customers`,
        title: "sidenav.customer",
        icon: UserOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "supplier",
        path: `${APP_PREFIX_PATH}/suppliers`,
        title: "sidenav.supplier",
        icon: ShopOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "order",
        path: `${APP_PREFIX_PATH}/order`,
        title: "sidenav.order",
        icon: ShoppingCartOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "order-list",
            path: `${APP_PREFIX_PATH}/order/list`,
            title: "sidenav.order.list",
            icon: ShoppingCartOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "order-request-list",
            path: `${APP_PREFIX_PATH}/order/request-list`,
            title: "sidenav.order.return-request-list",
            icon: PullRequestOutlined,
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "stock",
        path: `${APP_PREFIX_PATH}/stock`,
        title: "sidenav.stock",
        icon: ProductOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "stock-product-list",
            path: `${APP_PREFIX_PATH}/stock/product-list`,
            title: "sidenav.stock.product-list",
            icon: TagsOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "stock-adjustment-list",
            path: `${APP_PREFIX_PATH}/stock/adjustment-list`,
            title: "sidenav.stock.adjustment-list",
            icon: ProjectOutlined,
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "category_tag",
        path: `${APP_PREFIX_PATH}/category_tags`,
        title: "sidenav.category_tag",
        icon: PartitionOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "report",
        path: `${APP_PREFIX_PATH}/report`,
        title: "sidenav.report",
        icon: ProfileOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "report-sales-ranking",
            path: `${APP_PREFIX_PATH}/report/sales-ranking`,
            title: "sidenav.report.sales-ranking",
            icon: TagOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "report-inventory-alert",
            path: `${APP_PREFIX_PATH}/report/inventory-alert`,
            title: "sidenav.report.inventory-alert",
            icon: AlertOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "report-inventory-trend",
            path: `${APP_PREFIX_PATH}/report/inventory-trend`,
            title: "sidenav.report.inventory-trend",
            icon: AlertOutlined,
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "setting",
        path: `${APP_PREFIX_PATH}/setting`,
        title: "sidenav.setting",
        icon: SettingOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "setting-account",
            path: `${APP_PREFIX_PATH}/setting/account`,
            title: "sidenav.setting.account",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-general",
            path: `${APP_PREFIX_PATH}/setting/general`,
            title: "sidenav.setting.general",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-shipping-methods",
            path: `${APP_PREFIX_PATH}/setting/shipping-methods`,
            title: "sidenav.setting.shipping-methods",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-layout",
            path: `${APP_PREFIX_PATH}/setting/layout`,
            title: "sidenav.setting.layout",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-theme",
            path: `${APP_PREFIX_PATH}/setting/theme`,
            title: "sidenav.setting.theme",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-customer-pages",
            path: `${APP_PREFIX_PATH}/setting/custom-pages`,
            title: "sidenav.setting.custom-pages",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-language",
            path: `${APP_PREFIX_PATH}/setting/language`,
            title: "sidenav.setting.language",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
        ],
      }
    ],
  },
];

const superAdminNav = [
  {
    key: "admin",
    title: "sidenav.admin",
    breadcrumb: false,
    isGroupTitle: true,
    submenu: [
      {
        key: "user",
        path: `${APP_PREFIX_PATH}/users`,
        title: "sidenav.user",
        icon: UserOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "customer",
        path: `${APP_PREFIX_PATH}/customers`,
        title: "sidenav.customer",
        icon: UserOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "supplier",
        path: `${APP_PREFIX_PATH}/suppliers`,
        title: "sidenav.supplier",
        icon: ShopOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "order",
        path: `${APP_PREFIX_PATH}/order`,
        title: "sidenav.order",
        icon: ShoppingCartOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "order-list",
            path: `${APP_PREFIX_PATH}/order/list`,
            title: "sidenav.order.list",
            icon: ShoppingCartOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "order-request-list",
            path: `${APP_PREFIX_PATH}/order/request-list`,
            title: "sidenav.order.return-request-list",
            icon: PullRequestOutlined,
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "stock",
        path: `${APP_PREFIX_PATH}/stock`,
        title: "sidenav.stock",
        icon: ProductOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "stock-product-list",
            path: `${APP_PREFIX_PATH}/stock/product-list`,
            title: "sidenav.stock.product-list",
            icon: TagsOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "stock-adjustment-list",
            path: `${APP_PREFIX_PATH}/stock/adjustment-list`,
            title: "sidenav.stock.adjustment-list",
            icon: ProjectOutlined,
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "category_tag",
        path: `${APP_PREFIX_PATH}/category_tags`,
        title: "sidenav.category_tag",
        icon: PartitionOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "report",
        path: `${APP_PREFIX_PATH}/report`,
        title: "sidenav.report",
        icon: ProfileOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "report-sales-ranking",
            path: `${APP_PREFIX_PATH}/report/sales-ranking`,
            title: "sidenav.report.sales-ranking",
            icon: TagOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "report-inventory-alert",
            path: `${APP_PREFIX_PATH}/report/inventory-alert`,
            title: "sidenav.report.inventory-alert",
            icon: AlertOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "report-inventory-trend",
            path: `${APP_PREFIX_PATH}/report/inventory-trend`,
            title: "sidenav.report.inventory-trend",
            icon: AlertOutlined,
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "setting",
        path: `${APP_PREFIX_PATH}/setting`,
        title: "sidenav.setting",
        icon: SettingOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "setting-account",
            path: `${APP_PREFIX_PATH}/setting/account`,
            title: "sidenav.setting.account",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-general",
            path: `${APP_PREFIX_PATH}/setting/general`,
            title: "sidenav.setting.general",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-shipping-methods",
            path: `${APP_PREFIX_PATH}/setting/shipping-methods`,
            title: "sidenav.setting.shipping-methods",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-layout",
            path: `${APP_PREFIX_PATH}/setting/layout`,
            title: "sidenav.setting.layout",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-theme",
            path: `${APP_PREFIX_PATH}/setting/theme`,
            title: "sidenav.setting.theme",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-customer-pages",
            path: `${APP_PREFIX_PATH}/setting/custom-pages`,
            title: "sidenav.setting.custom-pages",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "setting-language",
            path: `${APP_PREFIX_PATH}/setting/language`,
            title: "sidenav.setting.language",
            icon: SettingOutlined,
            breadcrumb: false,
            submenu: [],
          },
        ],
      }
      // {
      //   key: "update",
      //   path: `${APP_PREFIX_PATH}/update`,
      //   title: "sidenav.update",
      //   icon: 0
      // }
    ],
  },
];

const navigationConfig = {
  adminNav: [...adminNav],
  superAdminNav: [...superAdminNav],
};

export default navigationConfig;
